// Automatically Generated in 2017-06-12 22:33:47.453434
#ifndef MAVLINK_PHOENIX_MAVLINK2ROS_H
#define MAVLINK_PHOENIX_MAVLINK2ROS_H
#include <drive_ros_msgs/mav_cc16_NOTIFICATION.h>
#include <drive_ros_msgs/mav_cc16_HEARTBEAT.h>
#include <drive_ros_msgs/mav_cc16_DEBUG.h>
#include <drive_ros_msgs/mav_cc16_TELEMETRY.h>
#include <drive_ros_msgs/mav_cc16_CONTROL_LIGHTS.h>
#include <drive_ros_msgs/mav_cc16_CONTROL_COMMAND.h>
#include <drive_ros_msgs/mav_cc16_IMU.h>
#include <drive_ros_msgs/mav_cc16_ODOMETER_ABS.h>
#include <drive_ros_msgs/mav_cc16_ODOMETER_RAW.h>
#include <drive_ros_msgs/mav_cc16_ODOMETER_DELTA.h>
#include <drive_ros_msgs/mav_cc16_ODOMETER_DELTA_RAW.h>
#include <drive_ros_msgs/mav_cc16_ODOMETER.h>
#include <drive_ros_msgs/mav_cc16_PROXIMITY.h>
#include <drive_ros_msgs/mav_cc16_PARKING_LOT.h>
#include <drive_ros_msgs/mav_cc16_CONFIG_REQUEST_COUNT.h>
#include <drive_ros_msgs/mav_cc16_CONFIG_REQUEST.h>
#include <drive_ros_msgs/mav_cc16_CONFIG_REQUEST_PARAMS.h>
#include <drive_ros_msgs/mav_cc16_CONFIG_COUNT.h>
#include <drive_ros_msgs/mav_cc16_CONFIG.h>
#include <drive_ros_msgs/mav_cc16_CONFIG_PARAM_INT.h>
#include <drive_ros_msgs/mav_cc16_CONFIG_PARAM_BOOL.h>
#include <drive_ros_msgs/mav_cc16_CONFIG_PARAM_FLOAT.h>
#include <drive_ros_msgs/mav_cc16_CONFIG_PARAM_SET_INT.h>
#include <drive_ros_msgs/mav_cc16_CONFIG_PARAM_SET_BOOL.h>
#include <drive_ros_msgs/mav_cc16_CONFIG_PARAM_SET_FLOAT.h>
#include <drive_ros_msgs/mav_cc16_COMMAND.h>
#include <drive_ros_msgs/mav_RAW_DATA.h>
#include <drive_ros_msgs/mav_cc16_TIMES.h>
#endif // MAVLINK_PHOENIX_MAVLINK2ROS_H
