sensor_cov:
    # array of coeffiencts for velocity (v) dependent covariances
    # example: [x_0, x_1, x_2]
    # resulting covariance = x_0 * v^0 + x_1 * v^1 + x_2 * v^2
    odo_pos_var:    [0]
    odo_vel_var:    [0.1]
    imu_acc_cov_xx: [0.2, 0.5]
    imu_acc_cov_yy: [0.2, 0.4]
    imu_acc_cov_zz: [0.2, 0.7]
    imu_gyr_cov_xx: [0.0002]
    imu_gyr_cov_yy: [0.0002]
    imu_gyr_cov_zz: [0.0002]
